cc_binary(
    name = "main_c",
    srcs = ["main.c"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "main_cc",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
)
